apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  FRONT_URL: "http://{{ .Values.host }}:{{ .Values.frontend.port }}"
  OPENSEARCH_HOST: "http://{{ .Values.opensearch.host }}"
  OPENSEARCH_PORT: "{{ .Values.opensearch.port | int }}"
