apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  FRONT_URL: "http://logs-app-frontend-service:5173"
  OPENSEARCH_HOST: "http://logs-app-opensearch-service"
  OPENSEARCH_PORT: "9200"
